# Generated by Django 4.2 on 2023-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='chat_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
