# Generated by Django 4.2 on 2023-05-20 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('chat_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True, unique=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=350, verbose_name='Ответ')),
                ('is_right', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox'), ('text', 'text')], default='radio', max_length=8)),
                ('text', models.CharField(max_length=350, verbose_name='Вопросы')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тест')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('all_question', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Предмет')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользовательское ID')),
            ],
            options={
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='question', chained_model_field='question', on_delete=django.db.models.deletion.CASCADE, to='quiz.answer')),
                ('question', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='test', chained_model_field='test', on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
                ('test', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, to='quiz.test')),
            ],
            options={
                'verbose_name_plural': 'Викторины',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Вопрос'),
        ),
    ]
