# Generated by Django 4.2 on 2023-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_number',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('RA', 'radio'), ('CH', 'checkbox'), ('TXT', 'text')], default='RA', max_length=3),
        ),
    ]
