# Generated by Django 4.2 on 2023-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_answer_alter_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='chat_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
